sudo: required
services:
  - docker
env:
  global:
    - SHA=$(git rev-parse HEAD)
    - CLOUDSDK_CORE_DISABLE_PROMPTS=1
before_install:
  # - openssl aes-256-cbc -K $encrypted_e3e2b59c8b93_key -iv $encrypted_e3e2b59c8b93_iv -in service-account.json.enc -out service-account.json -d
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  # - docker build -t aghabekyan374/react-test -f ./client/Dockerfile.dev ./client

script:
  - ls # testing

deploy:
  provider: script
  script: bash ./deploy.sh
  on:
    branch: docker