version: '2.0'


services:
  app:
    build: .
    command: bash -c "sleep 10 && python3 manage.py migrate && gunicorn -w 4 mobile_backend.wsgi:application -b 0.0.0.0:80"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mobile_backend
    ports:
      - '5433:5432'
