version: '2.0'


services:
  app:
    build: .
    command: bash -c "sleep 6 && python3 manage.py makemigrations && python3 manage.py migrate && gunicorn -w 4 mobile_backend.wsgi:application -b 0.0.0.0:80 --reload"
    volumes:
      - .:/code
    ports:
      - "80:80"
    depends_on:
      - postgres

  postgres:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=pass
      - POSTGRES_DB=mobile_backend
    volumes:
      - db-data:/var/lib/postgresql/data
    ports:
      - '5433:5432'

volumes:
  db-data: