# Generated by Django 2.2.4 on 2019-08-27 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FCMToken',
            fields=[
                ('user_id', models.CharField(max_length=200, primary_key=True, serialize=False)),
                ('token', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'main_fcm_token',
            },
        ),
    ]
